export const API_ROUTES = {
  BASE_URL: 'https://api.evurodog.com/api/',
  // BASE_URL: 'http://54.196.23.187:8081/api/',
  // BASE_URL: 'http://192.168.1.101:5000/api/',

  // BASE_URL: 'http://192.168.1.160:5000/api/',

  signUp: 'signUp',
  login: 'signIn',
  forgotPassword: 'forgotPassword',
  verifyOtp: 'verifyOtp',
  resendOtp: 'resendOtp',
  resetPassword: 'resetPassword',
  addPets: 'addPets',
  updatePet: 'updatePet',
  getPets: 'getPets',
  additionalInfo: 'additionalInfo',
  users: 'users',
  getAdminProducts: 'admin/getProducts',
  getWeeklyData: 'admin/getWeeklyData',
  getStatsOverview: 'admin/statsOverview',
  getUsersOrderPercentage: 'admin/usersOrderPercentage',
  getUserReports: 'getUserReports',
  revenue: 'admin/revenue',
  productRevenue: 'admin/productRevenue',
  addAdminProduct: 'admin/addProduct',
  editAdminProduct: 'admin/editProduct',
  deleteAdminProduct: 'admin/deleteProduct',
  getOrdersByFilter: 'admin/getOrdersByFilter',
  getOrderByID: 'getOrderById',
  updateOrderStatus: 'updateOrderStatus',
  editOrderStatus: 'admin/editOrderStatus',
  addLaunchPad: 'admin/launchPad',
  getProducts: 'getAvailableProducts',
  getProductsByDate: 'admin/getProductsByDate',
  getProductsByID: 'getAvailableProducts',
  getImageUrl: 'getImageUrl',
  getPetVideo: 'getPetVideo',
  allOnBoarding: 'getAllOnBoardingVideos',
  createOnBoarding: 'createOnBoardingVideoForMobile',
  updateOnBoarding: 'updateOnBoardingVideoForMobile',
  deleteOnBoarding: 'deleteOnBoardingVideo',
  getUsersWithOrders: 'admin/getUsersWithOrders?userType',
  deleteUserWithOrders: 'admin/deleteUser',
  dashBoard: 'getOnBoardingVideoForMobile',
  getTalents: 'talents',
  logoutUser: 'logoutUser',
  getLaunchpad: 'launchPad',
  getLaunchPadByUnAuthUser: 'getLaunchPadByUnAuthUser',
  addcomment: 'createlaunchpad/comments',
  likeLaunchpad: 'likeLaunchpad',
  changePassword: 'changePassword',
  createPost: 'createPost',
  getPosts: 'getPosts',
  deleteUser: 'deleteUser',
  createPetWalkerPlan: 'createPetWalkerPlan',
  getPetWalkerPlan: 'getPetWalkerPlan',
  getMyWalkerPlan: 'getMyWalkerPlan',
  getAllPets: 'getAllPets',
  likePost: 'likePost',
  addPostComment: 'postComment',
  likePostComment: {
    posts: 'posts',
    likeComment: 'likeComment',
  },
  toggleFavoriteTalent: 'toggleFavoriteTalent',
  getFavoriteTalents: 'favoriteTalents',
  editUserProfile: 'editUserProfile',
  searchDogWalkers: 'searchDogWalkers',
  getShorts: 'getShorts',
  likeShort: 'like',
  dislikeShort: 'dislike',
  createShort: 'createShort',
  updateAvailability: 'updateAvailability',
  createJob: 'createJob',
  getApplicationsForJob: 'getApplicationsForJob',
  applyForJob: 'applyForJob',
  getAvailableJobs: 'getAvailableJobs',
  getPostedJobs: 'getPostedJobs',
  placeOrder: 'placeOrder',
  addBillingAddress: 'addBillingAddress',
  getUserAddresses: 'getUserAddresses',
  deleteUserAddress: 'deleteUserAddress',
  editUserAddress: 'editUserAddress',
  getMyOrders: 'getMyOrders',
  acceptOrRejectWalkerPlan: 'acceptOrRejectWalkerPlan',
  updateWalkerPlanStatus: 'updateWalkerPlanStatus',
};
